### ISSUE TITLE
hook错误

### ISSUE THREAD

**Issue by zfdx123** [zhufucdev/MotionEmulator#52]
[ 2023-08-24T11:14:38.425    10332: 23431: 23431 I/LSPosed-Bridge  ]   Loading class com.zhufucdev.ws_plugin.hook.HookEntry_YukiHookXposedInit
[ 2023-08-24T11:14:38.637    10332: 23431: 23431 I/LSPosed-Bridge  ] [LocationHook][I][com.lptiyu.tanke]--> -- block other location methods --
[ 2023-08-24T11:14:38.661    10332: 23431: 23431 I/LSPosed-Bridge  ] [LocationHook][I][com.lptiyu.tanke]--> -- hook GPS --
[ 2023-08-24T11:14:38.669    10332: 23431: 23431 I/LSPosed-Bridge  ] [LocationHook][D][com.lptiyu.tanke]--> active update block finished with 16 methods hooked
[ 2023-08-24T11:14:38.681    10332: 23431: 23431 I/LSPosed-Bridge  ] [LocationHook][I][com.lptiyu.tanke]--> -- hook Amap --
[ 2023-08-24T11:14:38.688    10332: 23431: 23431 I/LSPosed-Bridge  ] [LocationHook][E][com.lptiyu.tanke]--> Failed to hook AMap location
[ 2023-08-24T11:14:38.688    10332: 23431: 23431 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.amap.api.location.AMapLocation" on path: DexPathList[[zip file "/data/app/~~hdg0Glk_H3PkCu2XQFIJfw==/com.lptiyu.tanke-mqgf9Z4jTw5A5KuD1s2BjQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~hdg0Glk_H3PkCu2XQFIJfw==/com.lptiyu.tanke-mqgf9Z4jTw5A5KuD1s2BjQ==/lib/arm64, /data/app/~~hdg0Glk_H3PkCu2XQFIJfw==/com.lptiyu.tanke-mqgf9Z4jTw5A5KuD1s2BjQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.zhufucdev.xposed.ExtensionKt.loadAMapLocation(Extension.kt:4)
	at com.zhufucdev.xposed.LocationHooker.hookAMap(LocationHooker.kt:483)
	at com.zhufucdev.xposed.LocationHooker.onHook(LocationHooker.kt:65)
	at com.highcapable.yukihookapi.hook.entity.YukiBaseHooker.assignInstance$yukihookapi_release(YukiBaseHooker.kt:53)
	at com.highcapable.yukihookapi.hook.param.PackageParam.loadHooker(PackageParam.kt:445)
	at com.zhufucdev.xposed.XposedScheduler$hook$1.onHook(XposedScheduler.kt:65)
	at com.highcapable.yukihookapi.hook.entity.YukiBaseHooker.assignInstance$yukihookapi_release(YukiBaseHooker.kt:53)
	at com.highcapable.yukihookapi.hook.param.PackageParam.loadHooker(PackageParam.kt:445)
	at com.zhufucdev.ws_plugin.hook.HookEntry$onHook$1.invoke(HookEntry.kt:19)
	at com.zhufucdev.ws_plugin.hook.HookEntry$onHook$1.invoke(HookEntry.kt:16)
	at com.highcapable.yukihookapi.hook.xposed.bridge.YukiXposedModule.onPackageLoaded(YukiXposedModule.kt:218)
	at com.highcapable.yukihookapi.hook.xposed.bridge.caller.YukiXposedModuleCaller.callOnPackageLoaded(YukiXposedModuleCaller.kt:93)
	at com.zhufucdev.ws_plugin.hook.HookEntry_Impl.callOnXposedModuleLoaded(HookEntry_Impl.kt:50)
	at com.zhufucdev.ws_plugin.hook.HookEntry_Impl.callOnXposedModuleLoaded$default(HookEntry_Impl.kt:35)
	at com.zhufucdev.ws_plugin.hook.HookEntry_Impl.callHandleLoadPackage(HookEntry_Impl.kt:75)
	at com.zhufucdev.ws_plugin.hook.HookEntry_YukiHookXposedInit.handleLoadPackage(HookEntry_YukiHookXposedInit.kt:37)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at h0.a(Unknown Source:271)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:250)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1398)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3100)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3092)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6962)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
[ 2023-08-24T11:14:38.695    10332: 23431: 23431 I/LSPosed-Bridge  ] [LocationHook][E][com.lptiyu.tanke]--> Failed to hook AMap Location Client
[ 2023-08-24T11:14:38.695    10332: 23431: 23431 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.amap.api.location.AMapLocationClient" on path: DexPathList[[zip file "/data/app/~~hdg0Glk_H3PkCu2XQFIJfw==/com.lptiyu.tanke-mqgf9Z4jTw5A5KuD1s2BjQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~hdg0Glk_H3PkCu2XQFIJfw==/com.lptiyu.tanke-mqgf9Z4jTw5A5KuD1s2BjQ==/lib/arm64, /data/app/~~hdg0Glk_H3PkCu2XQFIJfw==/com.lptiyu.tanke-mqgf9Z4jTw5A5KuD1s2BjQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.zhufucdev.xposed.ExtensionKt.loadAMapLocationClient(Extension.kt:12)
	at com.zhufucdev.xposed.LocationHooker.hookAMap(LocationHooker.kt:506)
	at com.zhufucdev.xposed.LocationHooker.onHook(LocationHooker.kt:65)
	at com.highcapable.yukihookapi.hook.entity.YukiBaseHooker.assignInstance$yukihookapi_release(YukiBaseHooker.kt:53)
	at com.highcapable.yukihookapi.hook.param.PackageParam.loadHooker(PackageParam.kt:445)
	at com.zhufucdev.xposed.XposedScheduler$hook$1.onHook(XposedScheduler.kt:65)
	at com.highcapable.yukihookapi.hook.entity.YukiBaseHooker.assignInstance$yukihookapi_release(YukiBaseHooker.kt:53)
	at com.highcapable.yukihookapi.hook.param.PackageParam.loadHooker(PackageParam.kt:445)
	at com.zhufucdev.ws_plugin.hook.HookEntry$onHook$1.invoke(HookEntry.kt:19)
	at com.zhufucdev.ws_plugin.hook.HookEntry$onHook$1.invoke(HookEntry.kt:16)
	at com.highcapable.yukihookapi.hook.xposed.bridge.YukiXposedModule.onPackageLoaded(YukiXposedModule.kt:218)
	at com.highcapable.yukihookapi.hook.xposed.bridge.caller.YukiXposedModuleCaller.callOnPackageLoaded(YukiXposedModuleCaller.kt:93)
	at com.zhufucdev.ws_plugin.hook.HookEntry_Impl.callOnXposedModuleLoaded(HookEntry_Impl.kt:50)
	at com.zhufucdev.ws_plugin.hook.HookEntry_Impl.callOnXposedModuleLoaded$default(HookEntry_Impl.kt:35)
	at com.zhufucdev.ws_plugin.hook.HookEntry_Impl.callHandleLoadPackage(HookEntry_Impl.kt:75)
	at com.zhufucdev.ws_plugin.hook.HookEntry_YukiHookXposedInit.handleLoadPackage(HookEntry_YukiHookXposedInit.kt:37)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:26)
	at h0.a(Unknown Source:271)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:250)
	at LSPHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1398)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3100)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3092)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6962)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2215)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by zfdx123** [comment]
hook对象为步道乐跑最新版本
