### ISSUE TITLE
[Bug]模拟功能不运行

### ISSUE THREAD

**Issue by 577fkj** [zhufucdev/MotionEmulator#75]
# 设备信息
Redmi K40s
Miui14 Android 13
Ksu + lsposed

软件版本：1.2.2
websocket插件：1.2.2

# 问题描述
使用websocket插件

无法开始定位，软件提示 `等待其他应用响应`

打开被hook软件闪退
```
11-11 22:02:40.493  9493  9534 D TrafficStats: tagSocket(85) with statsTag=0xffffffff, statsUid=-1
11-11 22:02:40.507  9493  9531 E AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
11-11 22:02:40.507  9493  9531 E AndroidRuntime: Process: com.autonavi.minimap, PID: 9493
11-11 22:02:40.507  9493  9531 E AndroidRuntime: javax.net.ssl.SSLHandshakeException: connection closed
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:363)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:243)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:220)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@907337c, Dispatchers.IO]
11-11 22:02:40.507  9493  9531 E AndroidRuntime: Caused by: java.io.EOFException: connection closed
11-11 22:02:40.507  9493  9531 E AndroidRuntime: 	... 22 more
```

关闭TLS后软件不闪退了，但是仍然无法定位

```
[ 2024-11-11T22:07:17.011     1000:  2134:  2584 I/LSPosed-Bridge  ] [ INFO] 11-11 22:07:17 (PmsHookTarget33) @shouldFilterApplication: query from com.huachenjie.shandong_school
[ 2024-11-11T22:07:42.856    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- block other location methods --
[ 2024-11-11T22:07:42.911    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook GPS --
[ 2024-11-11T22:07:42.930    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][D][com.autonavi.minimap]--> active update block finished with 16 methods hooked
[ 2024-11-11T22:07:42.963    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook Amap --
[ 2024-11-11T22:07:42.997    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook location --
[ 2024-11-11T22:07:43.232    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- block other location methods --
[ 2024-11-11T22:07:43.276    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook GPS --
[ 2024-11-11T22:07:43.294    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][D][com.autonavi.minimap]--> active update block finished with 16 methods hooked
[ 2024-11-11T22:07:43.321    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook Amap --
[ 2024-11-11T22:07:43.349    10242: 10135: 10172 I/LSPosed-Bridge  ] [Scheduler][I][com.autonavi.minimap]--> Provider offline. Waiting for data channel to become online
[ 2024-11-11T22:07:43.358    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook location --
[ 2024-11-11T22:07:43.588    10242: 10135: 10172 I/LSPosed-Bridge  ] [Scheduler][I][com.autonavi.minimap]--> Provider offline. Waiting for data channel to become online
[ 2024-11-11T22:07:43.873    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook Amap --
[ 2024-11-11T22:07:43.890    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][E][com.autonavi.minimap]--> Failed to hook AMap location
[ 2024-11-11T22:07:43.891    10242: 10135: 10135 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.amap.api.location.AMapLocation" on path: DexPathList[[zip file "/data/app/partner-com.autonavi.minimap_12/base.apk"],nativeLibraryDirectories=[/data/app/partner-com.autonavi.minimap_12/lib/arm64, /data/app/partner-com.autonavi.minimap_12/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.zhufucdev.xposed.ExtensionKt.loadAMapLocation(Extension.kt:4)
	at com.zhufucdev.xposed.LocationHooker.hookAMap(LocationHooker.kt:498)
	at com.zhufucdev.xposed.LocationHooker.access$hookAMap(LocationHooker.kt:54)
	at com.zhufucdev.xposed.LocationHooker$onHook$1$1$2.invoke(LocationHooker.kt:77)
	at com.zhufucdev.xposed.LocationHooker$onHook$1$1$2.invoke(LocationHooker.kt:76)
	at com.highcapable.yukihookapi.hook.core.YukiMemberHookCreator$MemberHookCreator$hook$beforeAfterHook$1.beforeHookedMember$yukihookapi_release(YukiMemberHookCreator.kt:631)
	at com.highcapable.yukihookapi.hook.core.api.factory.YukiHookDelegateFactoryKt.callBeforeHookedMember(YukiHookDelegateFactory.kt:99)
	at com.highcapable.yukihookapi.hook.core.api.compat.HookCompatHelper$compat$9.beforeHookedMethod(HookCompatHelper.kt:87)
	at TXTSxTgTqAaqAv.RzThD.V.XC_MethodHook.callBeforeHookedMethod(Unknown Source:0)
	at F.callback(Unknown Source:155)
	at LSPHooker_.onCreate(Unknown Source:11)
	at android.support.v4.app.BaseFragmentActivityDonut.onCreate(SourceFile:1)
	at android.support.v4.app.FragmentActivity.onCreate(SourceFile:2)
	at com.autonavi.map.activity.SplashActivity.onCreate(SourceFile:1)
	at android.app.Activity.performCreate(Activity.java:8458)
	at android.app.Activity.performCreate(Activity.java:8427)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1385)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3756)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3921)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2363)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
[ 2024-11-11T22:07:43.907    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][E][com.autonavi.minimap]--> Failed to hook AMap Location Client
[ 2024-11-11T22:07:43.907    10242: 10135: 10135 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.amap.api.location.AMapLocationClient" on path: DexPathList[[zip file "/data/app/partner-com.autonavi.minimap_12/base.apk"],nativeLibraryDirectories=[/data/app/partner-com.autonavi.minimap_12/lib/arm64, /data/app/partner-com.autonavi.minimap_12/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.zhufucdev.xposed.ExtensionKt.loadAMapLocationClient(Extension.kt:12)
	at com.zhufucdev.xposed.LocationHooker.hookAMap(LocationHooker.kt:532)
	at com.zhufucdev.xposed.LocationHooker.access$hookAMap(LocationHooker.kt:54)
	at com.zhufucdev.xposed.LocationHooker$onHook$1$1$2.invoke(LocationHooker.kt:77)
	at com.zhufucdev.xposed.LocationHooker$onHook$1$1$2.invoke(LocationHooker.kt:76)
	at com.highcapable.yukihookapi.hook.core.YukiMemberHookCreator$MemberHookCreator$hook$beforeAfterHook$1.beforeHookedMember$yukihookapi_release(YukiMemberHookCreator.kt:631)
	at com.highcapable.yukihookapi.hook.core.api.factory.YukiHookDelegateFactoryKt.callBeforeHookedMember(YukiHookDelegateFactory.kt:99)
	at com.highcapable.yukihookapi.hook.core.api.compat.HookCompatHelper$compat$9.beforeHookedMethod(HookCompatHelper.kt:87)
	at TXTSxTgTqAaqAv.RzThD.V.XC_MethodHook.callBeforeHookedMethod(Unknown Source:0)
	at F.callback(Unknown Source:155)
	at LSPHooker_.onCreate(Unknown Source:11)
	at android.support.v4.app.BaseFragmentActivityDonut.onCreate(SourceFile:1)
	at android.support.v4.app.FragmentActivity.onCreate(SourceFile:2)
	at com.autonavi.map.activity.SplashActivity.onCreate(SourceFile:1)
	at android.app.Activity.performCreate(Activity.java:8458)
	at android.app.Activity.performCreate(Activity.java:8427)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1385)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3756)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3921)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2363)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
[ 2024-11-11T22:07:43.918    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- block other location methods --
[ 2024-11-11T22:07:43.976    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook GPS --
[ 2024-11-11T22:07:43.997    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][D][com.autonavi.minimap]--> active update block finished with 16 methods hooked
[ 2024-11-11T22:07:44.041    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook Amap --
[ 2024-11-11T22:07:44.041    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook Amap --
[ 2024-11-11T22:07:44.055    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][E][com.autonavi.minimap]--> Failed to hook AMap location
[ 2024-11-11T22:07:44.055    10242: 10135: 10135 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.amap.api.location.AMapLocation" on path: DexPathList[[zip file "/data/app/partner-com.autonavi.minimap_12/base.apk"],nativeLibraryDirectories=[/data/app/partner-com.autonavi.minimap_12/lib/arm64, /data/app/partner-com.autonavi.minimap_12/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.zhufucdev.xposed.ExtensionKt.loadAMapLocation(Extension.kt:4)
	at com.zhufucdev.xposed.LocationHooker.hookAMap(LocationHooker.kt:498)
	at com.zhufucdev.xposed.LocationHooker.access$hookAMap(LocationHooker.kt:54)
	at com.zhufucdev.xposed.LocationHooker$onHook$1$1$2.invoke(LocationHooker.kt:77)
	at com.zhufucdev.xposed.LocationHooker$onHook$1$1$2.invoke(LocationHooker.kt:76)
	at com.highcapable.yukihookapi.hook.core.YukiMemberHookCreator$MemberHookCreator$hook$beforeAfterHook$1.beforeHookedMember$yukihookapi_release(YukiMemberHookCreator.kt:631)
	at com.highcapable.yukihookapi.hook.core.api.factory.YukiHookDelegateFactoryKt.callBeforeHookedMember(YukiHookDelegateFactory.kt:99)
	at com.highcapable.yukihookapi.hook.core.api.compat.HookCompatHelper$compat$9.beforeHookedMethod(HookCompatHelper.kt:87)
	at TXTSxTgTqAaqAv.RzThD.V.XC_MethodHook.callBeforeHookedMethod(Unknown Source:0)
	at F.callback(Unknown Source:155)
	at LSPHooker_.onCreate(Unknown Source:11)
	at android.support.v4.app.BaseFragmentActivityDonut.onCreate(SourceFile:1)
	at android.support.v4.app.FragmentActivity.onCreate(SourceFile:2)
	at com.autonavi.bundle.wingui.activity.PageSupportActivity.onCreate(SourceFile:1)
	at com.autonavi.wing.WingActivity.onCreate(SourceFile:6)
	at android.app.Activity.performCreate(Activity.java:8458)
	at android.app.Activity.performCreate(Activity.java:8427)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1385)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3756)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3921)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2363)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
[ 2024-11-11T22:07:44.069    10242: 10135: 10135 I/LSPosed-Bridge  ] [LocationHook][E][com.autonavi.minimap]--> Failed to hook AMap Location Client
[ 2024-11-11T22:07:44.069    10242: 10135: 10135 E/LSPosed-Bridge  ] java.lang.ClassNotFoundException: Didn't find class "com.amap.api.location.AMapLocationClient" on path: DexPathList[[zip file "/data/app/partner-com.autonavi.minimap_12/base.apk"],nativeLibraryDirectories=[/data/app/partner-com.autonavi.minimap_12/lib/arm64, /data/app/partner-com.autonavi.minimap_12/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at com.zhufucdev.xposed.ExtensionKt.loadAMapLocationClient(Extension.kt:12)
	at com.zhufucdev.xposed.LocationHooker.hookAMap(LocationHooker.kt:532)
	at com.zhufucdev.xposed.LocationHooker.access$hookAMap(LocationHooker.kt:54)
	at com.zhufucdev.xposed.LocationHooker$onHook$1$1$2.invoke(LocationHooker.kt:77)
	at com.zhufucdev.xposed.LocationHooker$onHook$1$1$2.invoke(LocationHooker.kt:76)
	at com.highcapable.yukihookapi.hook.core.YukiMemberHookCreator$MemberHookCreator$hook$beforeAfterHook$1.beforeHookedMember$yukihookapi_release(YukiMemberHookCreator.kt:631)
	at com.highcapable.yukihookapi.hook.core.api.factory.YukiHookDelegateFactoryKt.callBeforeHookedMember(YukiHookDelegateFactory.kt:99)
	at com.highcapable.yukihookapi.hook.core.api.compat.HookCompatHelper$compat$9.beforeHookedMethod(HookCompatHelper.kt:87)
	at TXTSxTgTqAaqAv.RzThD.V.XC_MethodHook.callBeforeHookedMethod(Unknown Source:0)
	at F.callback(Unknown Source:155)
	at LSPHooker_.onCreate(Unknown Source:11)
	at android.support.v4.app.BaseFragmentActivityDonut.onCreate(SourceFile:1)
	at android.support.v4.app.FragmentActivity.onCreate(SourceFile:2)
	at com.autonavi.bundle.wingui.activity.PageSupportActivity.onCreate(SourceFile:1)
	at com.autonavi.wing.WingActivity.onCreate(SourceFile:6)
	at android.app.Activity.performCreate(Activity.java:8458)
	at android.app.Activity.performCreate(Activity.java:8427)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1385)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3756)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3921)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2363)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8123)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
[ 2024-11-11T22:07:44.076    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook location --
[ 2024-11-11T22:07:44.347    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- block other location methods --
[ 2024-11-11T22:07:44.416    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook GPS --
[ 2024-11-11T22:07:44.464    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][D][com.autonavi.minimap]--> active update block finished with 16 methods hooked
[ 2024-11-11T22:07:44.503    10242: 10240: 10418 I/LSPosed-Bridge  ] [Scheduler][I][com.autonavi.minimap]--> Provider offline. Waiting for data channel to become online
[ 2024-11-11T22:07:44.508    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook Amap --
[ 2024-11-11T22:07:44.557    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook location --
[ 2024-11-11T22:07:44.722    10242: 10402: 10402 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- block other location methods --
[ 2024-11-11T22:07:44.788    10242: 10402: 10402 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook GPS --
[ 2024-11-11T22:07:44.812    10242: 10402: 10402 I/LSPosed-Bridge  ] [LocationHook][D][com.autonavi.minimap]--> active update block finished with 16 methods hooked
[ 2024-11-11T22:07:44.858    10242: 10240: 10375 I/LSPosed-Bridge  ] [Scheduler][I][com.autonavi.minimap]--> Provider offline. Waiting for data channel to become online
[ 2024-11-11T22:07:44.868    10242: 10402: 10402 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook Amap --
[ 2024-11-11T22:07:44.950    10242: 10402: 10402 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook location --
[ 2024-11-11T22:07:45.044    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- block other location methods --
[ 2024-11-11T22:07:45.100    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook GPS --
[ 2024-11-11T22:07:45.122    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][D][com.autonavi.minimap]--> active update block finished with 16 methods hooked
[ 2024-11-11T22:07:45.153    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook Amap --
[ 2024-11-11T22:07:45.189    10242: 10135: 10300 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- block other location methods --
[ 2024-11-11T22:07:45.191    10242: 10240: 10240 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook location --
[ 2024-11-11T22:07:45.244    10242: 10135: 10300 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook GPS --
[ 2024-11-11T22:07:45.263    10242: 10135: 10300 I/LSPosed-Bridge  ] [LocationHook][D][com.autonavi.minimap]--> active update block finished with 16 methods hooked
[ 2024-11-11T22:07:45.272    10242: 10402: 10402 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- block other location methods --
[ 2024-11-11T22:07:45.295    10242: 10135: 10300 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook Amap --
[ 2024-11-11T22:07:45.352    10242: 10135: 10300 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook location --
[ 2024-11-11T22:07:45.375    10242: 10402: 10402 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook GPS --
[ 2024-11-11T22:07:45.421    10242: 10402: 10402 I/LSPosed-Bridge  ] [LocationHook][D][com.autonavi.minimap]--> active update block finished with 16 methods hooked
[ 2024-11-11T22:07:45.448    10242: 10402: 10587 I/LSPosed-Bridge  ] [Scheduler][I][com.autonavi.minimap]--> Provider offline. Waiting for data channel to become online
[ 2024-11-11T22:07:45.459    10242: 10402: 10402 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook Amap --
[ 2024-11-11T22:07:45.478    10242: 10240: 10375 I/LSPosed-Bridge  ] [Scheduler][I][com.autonavi.minimap]--> Provider offline. Waiting for data channel to become online
[ 2024-11-11T22:07:45.495    10242: 10402: 10402 I/LSPosed-Bridge  ] [LocationHook][I][com.autonavi.minimap]--> -- hook location --
[ 2024-11-11T22:07:45.678    10242: 10135: 10438 I/LSPosed-Bridge  ] [Scheduler][I][com.autonavi.minimap]--> Provider offline. Waiting for data channel to become online
[ 2024-11-11T22:07:45.764    10242: 10402: 10603 I/LSPosed-Bridge  ] [Scheduler][I][com.autonavi.minimap]--> Provider offline. Waiting for data channel to become online
```

**Comment by SZCDSB** [comment]
想问一下用lsposed的话要勾选哪些应用？我勾选系统框架会开不了机

**Comment by 577fkj** [comment]
> 想问一下用lsposed的话要勾选哪些应用？我勾选系统框架会开不了机

勾选你要定位的软件

**Comment by 2767321434** [comment]
一样报这个错误，昨天还成功了，一次，感觉是作用域配置有问题，插件的作用域要勾选运动模拟器吗？

**Comment by 577fkj** [comment]
> 一样报这个错误，昨天还成功了，一次，感觉是作用域配置有问题，插件的作用域要勾选运动模拟器吗？

我只成功了一次，之后一直都等待相应，放弃了

**Comment by zhufucdev** [comment]
这种情况下，可以尝试用ContentProvider插件代替Websocket插件

**Comment by LazyXenon** [comment]
> 想问一下用lsposed的话要勾选哪些应用？我勾选系统框架会开不了机

官方说不需要 实测需要勾选系统框架才能使用，但是我三台小米设备都失败了 只要一台魅族20成功是 是不是说明小米手机不支持这个软件这个样子

**Comment by LazyXenon** [comment]
> > 想问一下用lsposed的话要勾选哪些应用？我勾选系统框架会开不了机
> 
> 官方说不需要 实测需要勾选系统框架才能使用，但是我三台小米设备都失败了 只要一台魅族20成功是 是不是说明小米手机不支持这个软件这个样子

这个软件是目前校园跑最优解 fake限制太多了
